name: Fast_API_deployment_workflow

on:
  push:
    branches:
      - main
      - development

jobs:
  deploy_applications:
    runs-on: self-hosted
    environment: ${{ github.ref_name }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Print Selected Branch
        run: |
          echo "The selected branch is: ${GITHUB_REF#refs/heads/}"
          echo "MY_ENV_VAR value is: $MY_ENV_VAR 1111"
          echo "test value ${MY_ENV_VAR}"
          echo ${{ vars.MY_ENV_VAR }}
          echo ${{ vars.MY_ENV_VAR }} this is running on our test machine
          echo test again
      - name: Check Runner Hostname
        run: hostname
      - name: Go to terraform folder
        run: |
          cd terraform
          ls -la
          terraform init
          terraform plan
          terraform apply --auto-approve
      - name: execute aws ecr login command
        run:  |
          aws ecr-public get-login-password --region us-east-1 > password.txt
          docker login --username AWS --password-stdin public.ecr.aws < password.txt
      - name: tag docker image
        run: docker tag fast_aws_image:latest public.ecr.aws/v6k1s9z9/demo-public-app-repo:latest
      - name: tag docker image
        run: docker push public.ecr.aws/v6k1s9z9/demo-public-app-repo:latest
      - name: update ecs service
        run: aws ecs update-service   --cluster demo-cluster   --service demo-app-service   --force-new-deployment   --region us-east-1
    